on:
    workflow_dispatch          
name: test
jobs:
  gbBuild:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
           ls
           ls -la
           pwd
           env
	   ls -l /home
